bidcruit/bidcruit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from candidate import views
from accounts import views as account_views
from candidate import views as candidate_views
from company import views as company_view
handler404 = 'accounts.views.handler404'
handler500 = 'accounts.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidate.urls')),
    path('agency/', include('agency.urls')),
    path('', account_views.bidcruit_home, name='bidcruit_home'),
    path('company/', include('company.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path("password_reset", auth_views.PasswordResetView.as_view(template_name='candidate/password/password_reset.html',
                                                                html_email_template_name='candidate/password/password_reset_email.html'),
         name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='candidate/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="candidate/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='candidate/password/password_reset_complete.html'),
         name='password_reset_complete'),
    path('tinymce/', include('tinymce.urls')),
    path('<str:url>/', candidate_views.timeline, name="timeline"),
    path('view_job/<int:id>',company_view.view_job,name="view_job"),
    path('apply_job/<int:id>/',candidate_views.apply_job,name='apply_job'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bidcruit/candidate/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'candidate'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('signup', views.ragister, name="signup"),
    path('signup/<str:referral>', views.referral_signup, name="referral_signup"),
    url(r'^country/(?P<id>\d+)/$', views.state_view),
    url(r'^state/(?P<id>\d+)/$', views.city_view),
    url(r'^cities_by_country/(?P<id>\d+)/$', views.cities_by_country),
    url(r'^preference_cities_by_country/(?P<id>\d+)/$', views.preference_cities_by_country),
    path('candidate_profile', views.candidate_profile, name="candidate_profile"),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    path('/<str:url>/', views.timeline, name="timeline"),
   
    # charts
    path('statistics/', views.statistics_view, name="candidate_statistics"),
    path('chart/filter-options/', views.get_filter_options, name='chart-filter-options'),
    path('chart/payment-method/', views.payment_method_chart, name='chart-payment-method'),
    path('chart/job-experience/', views.job_exp_Chart, name='chart-job-experience'),
    path('chart/edu-percentage/', views.edu_per_chart, name='chart-edu-percentage'),
    path('charts', views.charts, name='charts'),


    # Wizard
    path('upload_resume/personal_detail_temp', views.personal_detail_temp, name="personal_detail_temp"),
    path('upload_resume/education_temp', views.education_temp, name="education_temp"),
    path('upload_resume/work_experience_temp', views.work_experience_temp, name="work_experience_temp"),
    path('upload_resume/skill_temp', views.skill_temp, name="skill_temp"),
    path('upload_resume/other_temp', views.other_temp, name="other_temp"),
    path('upload_resume/remove_record', views.remove_record, name="remove_record"),
    path('upload_resume/save_resume', views.save_resume, name="save_resume"),
    path('create_resume_pass/', views.create_resume_pass, name="create_resume_pass"),
    path('update_resume_pass/', views.update_resume_pass, name="update_resume_pass"),
    path('update_share_url/',views.update_share_url,name="update_share_url"),
    path('check_sharing_url_is_valid',views.check_sharing_url_is_valid,name="check_sharing_url_is_valid"),

    # Dashboard
    path('upload_resume_add/<str:url>', views.upload_resume, name='upload_resume_add'),
    path('add_profile/',views.add_profile,name='add_profile'),
    path('add_profile_detail/<str:url>',views.add_profile_detail,name='add_profile_detail'),
    path('toggle_profile/', views.toggle_profile, name="toggle_profile"),
    path('toggle_field_state/', views.toggle_field_state, name="toggle_field_state"),
    path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('job_preference/', views.candidate_job_preference, name="job_preference"),

    #  Request
    path('hire_request/', views.hire_request, name="hire_request"),
    path('accept_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.accept_request, name="accept_request"),
    path('reject_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.reject_request, name="reject_request"),
    path('data_accept_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_accept_request, name="data_accept_request"),
    path('data_reject_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_reject_request, name="data_reject_request"),

    path('file_download',views.file_download,name="file_download"),
    path('look_for_job_check/', views.look_for_job_check, name="look_for_job_check"),
    path('delete_exp_document', views.delete_exp_doc, name="delete_exp_doc"),
    path('candidate_resume_update/', views.candidate_resume_update, name="candidate_resume_update"),

    # Profile update
    # path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('download_folder/<int:candidate_id>/',views.download_folder,name="download_folder"),
    path('test_redirect/', views.test_redirect, name="test_redirect"),


    #apply job
    path('add_apply_candidate/', views.add_apply_candidate, name='add_apply_candidate'),
    path('applied_job_list/', views.applied_job_list, name='applied_job_list'),
    path('candidate_jcr/<int:id>/<int:job_id>', views.candidate_jcr, name='candidate_jcr'),
    path('applied_job_detail/<int:id>', views.applied_job_detail, name='applied_job_detail'),
    path("prequisites_view/<int:id>/<int:job_id>", views.prequisites_view, name="prequisites_view"),

]

bidcruit/chat/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
app_name= 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("chat/<str:email>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

bidcruit/company/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'company'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('signup', views.ragister, name="signup"),
    url(r'^verify_otp/$', views.verify_otp, name='verify_otp'),
    path('candidate_hire', views.candidate_hire, name='candidate_hire'),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    path('company_login_direct', views.company_login_direct, name="company_login_direct"),
    path('candidate_list_view', views.candidate_list_view, name="candidate_list_view"),
    path('user_login_email_popup', views.user_login_email_popup, name="user_login_email_popup"),
    path('user_login_password_popup', views.user_login_password_popup, name="user_login_password_popup"),
    path('user_login_verify_otp_popup', views.user_login_verify_otp_popup, name="user_login_verify_otp_popup"),
    path('candidate_preference_check', views.candidate_preference_check, name="candidate_preference_check"),

    # candidate search urls
    path('search', views.search, name="search"),
    path('search_result', views.search_result, name="search_result"),
    path('advanced_search', views.advanced_search, name="advanced_search"),
    path('get_page_no', views.get_page_no, name="get_page_no"),
    path('get_cities/',views.get_cities,name='get_cities'),
    path('get_skills/',views.get_skills,name='get_skills'),
    path('get_degrees/',views.get_degrees,name='get_degrees'),
    path('add_edit_profile/',views.add_edit_profile,name='add_edit_profile'),
    path('file_request',views.file_request,name="file_request"),
    # path('demo',views.demo,name='demo'),
    path('candidate_detail/<str:url>',views.candidate_detail,name='candidate_detail'),
    path('hire_request/', views.doc_request, name="hire_request"),
    path('document_request/',views.document_request,name='document_request'),
    path('company_profile/',views.company_profile,name='company_profile'),
    path('shortlist/',views.shortlist_candidate,name='shortlist_candidate'),

    # ############################## ATS ####################################

    #   Candidates
    path('all_countries/', views.all_countries, name='all_countries'),
    path('all_states/<str:country_id>', views.all_states, name='all_states'),
    path('all_cities/<str:state_id>', views.all_cities, name='all_cities'),
    path('add_candidate/', views.add_candidate, name='add_candidate'),
    path('all_candidates/', views.all_candidates, name='all_candidates'),
    path('view_candidate/<str:candidate_id>', views.view_candidate, name='view_candidate'),
    path('internal_candidate_notes/', views.internal_candidate_notes, name='internal_candidate_notes'),

    #  Job Creation
    path('job_creation/', views.job_creation, name='job_creation'),
    path('job_openings_table/', views.job_openings_table, name='job_openings_table'),
    path('job_openings_requests/', views.job_openings_requests, name='job_openings_requests'),

    # Template Creation
    path('template_listing/', views.template_listing, name='template_listing'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('update_category/', views.update_category, name='update_category'),
    path('get_category/', views.get_category, name='get_category'),
    # path('create_template/', views.create_template, name='create_template'),
    path('edit_template/', views.edit_template, name='edit_template'),
    path('delete_template/', views.delete_template, name='delete_template'),

    # Pre requisites
    path("pre_requisites/", views.pre_requisites, name="pre_requisites"),
    path("save_pre_requisites/", views.save_pre_requisites, name="save_pre_requisites"),

    # JCR
    path('jcr/', views.jcr, name='jcr'),
    path('insert_jcr/', views.insert_jcr, name='insert_jcr'),
    path('remove_jcr/', views.remove_jcr, name='remove_jcr'),
    path('remove_sub_jcr/', views.remove_sub_jcr, name='remove_sub_jcr'),
    path('jcr_preview/', views.jcr_preview, name='jcr_preview'),

    #  Workflow Management
    path("workflow_list/", views.workflow_list, name="workflow_list"),
    path("create_workflow/", views.create_workflow, name="create_workflow"),
    path("edit_workflow/<int:id>", views.edit_workflow, name="edit_workflow"),
    path("workflow_configuration/", views.workflow_configuration, name="workflow_configuration"),
    path("get_workflow_data/", views.get_workflow_data, name="get_workflow_data"),
    path("workflow_selection/<int:id>", views.workflow_selection, name="workflow_selection"),

    path("created_job_view/<int:id>", views.created_job_view, name="created_job_view"),

]

bidcruit/company/forms.py
from os import execl
from django import forms
from candidate.models import City, Degree, NoticePeriod



notice_periods= NoticePeriod.objects.all()
notice_period_choices=[]

for i in notice_periods:
    notice_period_choices.append((i.id,i.notice_period))

# cities= City.objects.all()
# city_names =[]
# for i in cities:
#     city_names.append((i.id,i.city_name))
# city_names=[]
# education_choices= []
class CandidateForm(forms.Form):

    notice_period = ((1,'One Day'),(2,'Two Days'),(3,'Three Days'),(4,'Four Days'),(5,'Five Days'),(6,'Six Days'))
    include_skills = forms.ChoiceField(choices=[],required=False,label='Skills you want in your candidate',widget=forms.Select(attrs={'class': 'form-select select2_skill','multiple':'multiple','style':'width:100%'}))
    exclude_skills = forms.ChoiceField(choices=[],required=False,label='Skills you don\'t want in your candidate',widget=forms.Select(attrs={'class': 'form-select select2_skill','multiple':'multiple','style':'width:100%'}))
    notice_period =forms.ChoiceField(required=False,label='Notice Period',choices = notice_period_choices,widget=forms.Select(attrs={'class':'form-select select2'}))
    preferred_cities = forms.ChoiceField(required=False,label='Preferred cities',widget=forms.Select(attrs={'class': 'form-select select2_cities','multiple':'multiple','style':'width:100%'}))
    minimum_experience = forms.IntegerField(required=False,label='Minimum experience',widget=forms.NumberInput(attrs={'class': 'form-control'}))
    maximum_experience = forms.IntegerField(required=False,label='Maximum experience',widget=forms.NumberInput(attrs={'class': 'form-control'}))
    current_city = forms.ChoiceField(choices=[],required=False,label='Current City',widget=forms.Select(attrs={'class': 'form-select select2_cities','style':'width:100%'}))
    # working_company = forms.CharField(required=False,label='Working company',max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
    education = forms.ChoiceField(choices=[],required=False,label='Education',widget=forms.Select(attrs={'class': 'form-control select2_degrees','multiple':'multiple','style':'width:100%'}))

    def __init__(self, current_city=None,minimum_experience=None,maximum_experience=None,education_choices=None,preferred_cities= None,include_skills= None,exclude_skills= None,notice_period = None, *args, **kwargs):
        super(CandidateForm, self).__init__(*args, **kwargs)
        if current_city:
            print('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$',current_city)
            self.fields['current_city'].choices = current_city
        if minimum_experience:
            self.fields['minimum_experience'].initial = minimum_experience
        if maximum_experience:
            self.fields['maximum_experience'].initial = maximum_experience
        # if education_choices:
        #     print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&",education_choices)
        #     self.fields['education'].choices = education_choices
        if education_choices:
            print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&",education_choices)
            print(self.fields['education'].choices)
            self.fields['education'].choices =  education_choices
            self.fields['education'].initial = education_choices
            # self.fields['education'].initial = education_choices\
            # self.initial['education'] = education_choices
            print(self.fields['education'].choices)
            print(self.fields['education'])
        if preferred_cities:
            self.fields['preferred_cities'].choices = preferred_cities
        if include_skills:
            options = []
            for i in include_skills:
                options.append((i,i))
            self.fields['include_skills'].choices = options
        if exclude_skills:
            options = []
            for i in exclude_skills:
                options.append((i,i))
            self.fields['exclude_skills'].choices = options
        if notice_period:
            self.fields['notice_period'].initial = notice_period

# 
# class CandidateForm(forms.Form):
#     notice_period = ((1,'One Day'),(2,'Two Days'),(3,'Three Days'),(4,'Four Days'),(5,'Five Days'),(6,'Six Days'))
#     include_skills = forms.CharField(label='Skills you want in your candidate', max_length=100,widget=forms.TextInput(attrs={'class': 'form-control js-example-basic-multiple js-states'}))
#     exclude_skills = forms.CharField(label='Skills you want in your candidate', max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
#     notice_period =forms.ChoiceField(label='Notice Period',choices = notice_period,widget=forms.Select(attrs={'class':'form-select'}))
#     preferred_cities = forms.CharField(label='Preferred cities',max_length=40,widget=forms.TextInput(attrs={'class': 'form-control'}))
#     minimum_experience = forms.IntegerField(label='Minimum experience')
#     maximum_experience = forms.IntegerField(label='Maximum experience')
#     current_city = forms.CharField(label='Current City',max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
#     working_company = forms.CharField(label='Working company',max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))
#     education = forms.CharField(label='education',max_length=100,widget=forms.TextInput(attrs={'class': 'form-control'}))

bidcruit/company/templates/company/Dashbord-company-profile.html
{% extends 'company/base.html' %}
{% load static %}
{% load candidate_extras %}
{% block title %}Company Profile{% endblock %}

{% block main %}
			
		<div class="container-fluid">
		<br>
				<!-- Main-content-body -->
				<div class="main-content-body edit-profile-wrap">


					<!-- row -->
					<div class="row row-sm">
						<div class="col-md-12 col-xl-12 col-lg-12">
							<div class="card">

								<div class="card-body ">
								<div class="view-company-profile row">
                                    <div class="col-lg-3 col-sm-4 col-xs-12">
                                        <div class="sidebar-com-prof-view">
                                            <div class="logo-view-fp">
                                                <img src="{{profile.company_logo.url}}">
                                            </div>
                                            <div class="logo-view-scan">
                                                <img src="{% static 'assets/img/scancode.png' %}">
                                            </div>
                                            <div class="social-for-company-view">
                                                <ul>
                                                    <li>
                                                        <a href="#"><i  class="fab fa-facebook-f"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i  class="fab fa-instagram"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i class="fab fa-twitter"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i  class="fab fa-linkedin-in"></i></a>
                                                    </li>
                                                    <li>
                                                        <a href="#"><i  class="fab fa-behance"></i></a>
                                                    </li>
                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="col-lg-9 col-sm-8 col-xs-12">
                                        <div class="rgt-detail-of-company">
                                            <div class="heading-for-com-detail">
                                                <h2>{{profile.company_id.company_name}} </h2>
                                                <h3>{{profile.compnay_type}}</h3>
                                            </div>
                                            <div class="detailed-view">
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-globe"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.company_id.website}} {% if request.user.is_company %}<span class="edit-icn-d"><a href="{% url 'company:add_edit_profile' %}"><i data-v-e08301e8="" class="fas fa-edit"></i></a></span>{% endif %}</p>
                                                    </div>
                                                </div>
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-envelope-open-text"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.company_id.email}}</p>
                                                    </div>
                                                </div>
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-phone-volume"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.contact_no1}}/{{profile.contact_no2}}</p>
                                                    </div>
                                                </div>
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-building"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.compnay_type}}</p>
                                                    </div>
                                                </div>
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-map-marker-alt"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.address}},{{profile.city.city_name}}-{{profile.zip_code}},{{profile.state.state_name}},{{profile.country.country_name}}.</p>
                                                    </div>
                                                </div>

                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-calendar-alt"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>Founded Year - {{profile.founded_year}}</p>
                                                    </div>
                                                </div>
                                                
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-users"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.employee_count}}</p>
                                                    </div>
                                                </div>
                                                
                                                <div class="row-sub-detail">
                                                    <div class="detal-icon">
                                                        <i data-v-e08301e8="" class="fas fa-magic"></i>
                                                    </div>
                                                    <div class="rgt-ftl-view">
                                                        <p>{{profile.speciality}}.</p>
                                                    </div>
                                                </div>
                                                
                                            </div>

                                        </div>
                                    </div>
                                </div>
									</div>
								</div>
							</div>
						</div>

					</div>
					<!-- /row -->
				</div>

{% endblock %}

bidcruit/company/templates/company/candidate_index.html
<!DOCTYPE html>
{%load static%}
{%load custom_filters %}
<html>
    <head>
        <title>Search for candidates </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />

    </head>

    <body>
        <form action="{%url 'company:search'%}" method="POST">
            {%csrf_token%}
            <input class="form-control" type="text" name="candidate_search" placeholder=" Enter your skills requirements" >
            <!-- <input class="form-select" type="select" class="select2_cities" name="candidate_search_city" placeholder=" Enter City" > -->
            <select name="candidate_search_city" class="form-select select2_cities" style="width: 100%;" id=""></select>
            <input type="submit" value="submit">
        </form>

 
        
        {%if no_of_candidates == 0 %}
        <h3>No candidate matches your criteria!</h3>

        {% else %}
            {%if no_of_candidates%}
                Candidates fullfilling your criteria
                    {%for i in users%}
                        
                        {%for j in i%}
                        <br>
                        <div>
                            Name = {{j.first_name}} {{j.last_name}}<br>
                            Email = {{j.email}}<br>
                            Education = {{j|get_education_title}}<br>
                            Previous Job Title = {{j|get_job_title}}<br>
                            Preferred Job Locations = {{j|get_preferred_job_locations}}<br>
                        </div>
                        {%endfor%}
            

                    {%endfor%}
            {%endif%}    
        {%endif%}
    </body>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
   
    <script>
        $(document).ready(function()
			{
                console.log("onload is called")
                $(".select2_cities").select2({
						tags:true,
					});
                console.log("first part is done")

                $('.select2_cities').select2({
                    ajax: {
                        url:"/company/get_cities",
                        dataType: 'json',
                        processResults: function (data) {
                            return {
                                results: $.map(data, function (item) {
                                    return {id: item.id, text: item.city_name};
                            })
                        };
                    }
                },
                minimumInputLength: 1
                });
            });

    </script>
</html>

bidcruit/company/templates/company/city.html
<select name="city" class="custom-select form-control " id="c_city">
    {%for city in cities%}
         <option value="{{city.id}}">{{city.city_name}}</option>
    {%endfor%}
</select>

bidcruit/company/templates/company/state.html
<select name="state" id="c_state" class="custom-select form-control " onchange="getCity(this.value)" >
{%for state in states%}
  <option value="{{state.id}}" >{{state.state_name}}</option>
        {%endfor%}
		</select>