bidcruit/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'accounts'

urlpatterns = [
    path('resend_otp/', views.resend_otp, name="resend_otp"),
    url(r'^user_login_password/$', views.user_login_password, name='user_login_password'),
    url(r'^$', views.user_login_email, name='signin'),
    url(r'^verify_otp/$', views.verify_otp, name='verify_otp'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    url(r'^activate/('
        r'?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    # url(r'^activate_account_confirmation/$', views.activate_account_confirmation, name='activate_account_confirmation'),
    path('back_to_home',views.back_to_home,name='back_to_home'),

    #ATS
    path('apply_job_cadidate_sendotp',views.apply_job_cadidate_sendotp,name='apply_job_cadidate_sendotp'),
    path('job_apply_verify_otp',views.job_apply_verify_otp,name='job_apply_verify_otp'),

    
]

bidcruit/bidcruit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from candidate import views
from accounts import views as account_views
from candidate import views as candidate_views
from company import views as company_view
handler404 = 'accounts.views.handler404'
handler500 = 'accounts.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidate.urls')),
    path('agency/', include('agency.urls')),
    path('', account_views.bidcruit_home, name='bidcruit_home'),
    path('company/', include('company.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path("password_reset", auth_views.PasswordResetView.as_view(template_name='candidate/password/password_reset.html',
                                                                html_email_template_name='candidate/password/password_reset_email.html'),
         name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='candidate/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="candidate/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='candidate/password/password_reset_complete.html'),
         name='password_reset_complete'),
    path('tinymce/', include('tinymce.urls')),
    path('<str:url>/', candidate_views.timeline, name="timeline"),
    path('view_job/<int:id>',company_view.view_job,name="view_job"),
    path('apply_job/<int:id>/',candidate_views.apply_job,name='apply_job'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bidcruit/candidate/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'candidate'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('signup', views.ragister, name="signup"),
    path('signup/<str:referral>', views.referral_signup, name="referral_signup"),
    url(r'^country/(?P<id>\d+)/$', views.state_view),
    url(r'^state/(?P<id>\d+)/$', views.city_view),
    url(r'^cities_by_country/(?P<id>\d+)/$', views.cities_by_country),
    url(r'^preference_cities_by_country/(?P<id>\d+)/$', views.preference_cities_by_country),
    path('candidate_profile', views.candidate_profile, name="candidate_profile"),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    path('/<str:url>/', views.timeline, name="timeline"),
   
    # charts
    path('statistics/', views.statistics_view, name="candidate_statistics"),
    path('chart/filter-options/', views.get_filter_options, name='chart-filter-options'),
    path('chart/payment-method/', views.payment_method_chart, name='chart-payment-method'),
    path('chart/job-experience/', views.job_exp_Chart, name='chart-job-experience'),
    path('chart/edu-percentage/', views.edu_per_chart, name='chart-edu-percentage'),
    path('charts', views.charts, name='charts'),


    # Wizard
    path('upload_resume/personal_detail_temp', views.personal_detail_temp, name="personal_detail_temp"),
    path('upload_resume/education_temp', views.education_temp, name="education_temp"),
    path('upload_resume/work_experience_temp', views.work_experience_temp, name="work_experience_temp"),
    path('upload_resume/skill_temp', views.skill_temp, name="skill_temp"),
    path('upload_resume/other_temp', views.other_temp, name="other_temp"),
    path('upload_resume/remove_record', views.remove_record, name="remove_record"),
    path('upload_resume/save_resume', views.save_resume, name="save_resume"),
    path('create_resume_pass/', views.create_resume_pass, name="create_resume_pass"),
    path('update_resume_pass/', views.update_resume_pass, name="update_resume_pass"),
    path('update_share_url/',views.update_share_url,name="update_share_url"),
    path('check_sharing_url_is_valid',views.check_sharing_url_is_valid,name="check_sharing_url_is_valid"),

    # Dashboard
    path('upload_resume_add/<str:url>', views.upload_resume, name='upload_resume_add'),
    path('add_profile/',views.add_profile,name='add_profile'),
    path('add_profile_detail/<str:url>',views.add_profile_detail,name='add_profile_detail'),
    path('toggle_profile/', views.toggle_profile, name="toggle_profile"),
    path('toggle_field_state/', views.toggle_field_state, name="toggle_field_state"),
    path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('job_preference/', views.candidate_job_preference, name="job_preference"),

    #  Request
    path('hire_request/', views.hire_request, name="hire_request"),
    path('accept_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.accept_request, name="accept_request"),
    path('reject_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.reject_request, name="reject_request"),
    path('data_accept_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_accept_request, name="data_accept_request"),
    path('data_reject_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_reject_request, name="data_reject_request"),

    path('file_download',views.file_download,name="file_download"),
    path('look_for_job_check/', views.look_for_job_check, name="look_for_job_check"),
    path('delete_exp_document', views.delete_exp_doc, name="delete_exp_doc"),
    path('candidate_resume_update/', views.candidate_resume_update, name="candidate_resume_update"),

    # Profile update
    # path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('download_folder/<int:candidate_id>/',views.download_folder,name="download_folder"),
    path('test_redirect/', views.test_redirect, name="test_redirect"),


    #apply job
    path('add_apply_candidate/', views.add_apply_candidate, name='add_apply_candidate'),
    path('applied_job_list/', views.applied_job_list, name='applied_job_list'),
    path('candidate_jcr/<int:id>/<int:job_id>', views.candidate_jcr, name='candidate_jcr'),
    path('applied_job_detail/<int:id>', views.applied_job_detail, name='applied_job_detail'),
    path("prequisites_view/<int:id>/<int:job_id>", views.prequisites_view, name="prequisites_view"),

]

bidcruit/chat/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
app_name= 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("chat/<str:email>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

bidcruit/company/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'company'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('signup', views.ragister, name="signup"),
    url(r'^verify_otp/$', views.verify_otp, name='verify_otp'),
    path('candidate_hire', views.candidate_hire, name='candidate_hire'),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    path('company_login_direct', views.company_login_direct, name="company_login_direct"),
    path('candidate_list_view', views.candidate_list_view, name="candidate_list_view"),
    path('user_login_email_popup', views.user_login_email_popup, name="user_login_email_popup"),
    path('user_login_password_popup', views.user_login_password_popup, name="user_login_password_popup"),
    path('user_login_verify_otp_popup', views.user_login_verify_otp_popup, name="user_login_verify_otp_popup"),
    path('candidate_preference_check', views.candidate_preference_check, name="candidate_preference_check"),

    # candidate search urls
    path('search', views.search, name="search"),
    path('search_result', views.search_result, name="search_result"),
    path('advanced_search', views.advanced_search, name="advanced_search"),
    path('get_page_no', views.get_page_no, name="get_page_no"),
    path('get_cities/',views.get_cities,name='get_cities'),
    path('get_skills/',views.get_skills,name='get_skills'),
    path('get_degrees/',views.get_degrees,name='get_degrees'),
    path('add_edit_profile/',views.add_edit_profile,name='add_edit_profile'),
    path('file_request',views.file_request,name="file_request"),
    # path('demo',views.demo,name='demo'),
    path('candidate_detail/<str:url>',views.candidate_detail,name='candidate_detail'),
    path('hire_request/', views.doc_request, name="hire_request"),
    path('document_request/',views.document_request,name='document_request'),
    path('company_profile/',views.company_profile,name='company_profile'),
    path('shortlist/',views.shortlist_candidate,name='shortlist_candidate'),

    # ############################## ATS ####################################

    #   Candidates
    path('all_countries/', views.all_countries, name='all_countries'),
    path('all_states/<str:country_id>', views.all_states, name='all_states'),
    path('all_cities/<str:state_id>', views.all_cities, name='all_cities'),
    path('add_candidate/', views.add_candidate, name='add_candidate'),
    path('all_candidates/', views.all_candidates, name='all_candidates'),
    path('view_candidate/<str:candidate_id>', views.view_candidate, name='view_candidate'),
    path('internal_candidate_notes/', views.internal_candidate_notes, name='internal_candidate_notes'),

    #  Job Creation
    path('job_creation/', views.job_creation, name='job_creation'),
    path('job_openings_table/', views.job_openings_table, name='job_openings_table'),
    path('job_openings_requests/', views.job_openings_requests, name='job_openings_requests'),

    # Template Creation
    path('template_listing/', views.template_listing, name='template_listing'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('update_category/', views.update_category, name='update_category'),
    path('get_category/', views.get_category, name='get_category'),
    # path('create_template/', views.create_template, name='create_template'),
    path('edit_template/', views.edit_template, name='edit_template'),
    path('delete_template/', views.delete_template, name='delete_template'),

    # Pre requisites
    path("pre_requisites/", views.pre_requisites, name="pre_requisites"),
    path("save_pre_requisites/", views.save_pre_requisites, name="save_pre_requisites"),

    # JCR
    path('jcr/', views.jcr, name='jcr'),
    path('insert_jcr/', views.insert_jcr, name='insert_jcr'),
    path('remove_jcr/', views.remove_jcr, name='remove_jcr'),
    path('remove_sub_jcr/', views.remove_sub_jcr, name='remove_sub_jcr'),
    path('jcr_preview/', views.jcr_preview, name='jcr_preview'),

    #  Workflow Management
    path("workflow_list/", views.workflow_list, name="workflow_list"),
    path("create_workflow/", views.create_workflow, name="create_workflow"),
    path("edit_workflow/<int:id>", views.edit_workflow, name="edit_workflow"),
    path("workflow_configuration/", views.workflow_configuration, name="workflow_configuration"),
    path("get_workflow_data/", views.get_workflow_data, name="get_workflow_data"),
    path("workflow_selection/<int:id>", views.workflow_selection, name="workflow_selection"),

    path("created_job_view/<int:id>", views.created_job_view, name="created_job_view"),

]

bidcruit/candidate/templates/candidate/activate_account_confirmation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="images/favicon.ico">

        <title>Maximum Admin - Dashboard</title>

        <!-- Bootstrap v4.1.3.stable -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/bootstrap/dist/css/bootstrap.css' %}">

        <!-- font awesome -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/font-awesome/css/font-awesome.css'%}">

        <!-- ionicons -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/Ionicons/css/ionicons.css'%}">

        <!-- theme style -->
        <link rel="stylesheet" href="{% static 'css/master_style.css'%}">

        <!-- maximum_admin skins. choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="{% static 'css/skins/_all-skins.css'%}">

        <!-- morris chart -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/morris.js/morris.css' %}">

        <!-- jvectormap -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/jvectormap/jquery-jvectormap.css' %}">

        <!-- date picker -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.css'%}">

        <!-- daterange picker -->
        <link rel="stylesheet" href="{% static 'assets/vendor_components/bootstrap-daterangepicker/daterangepicker.css'%}">

        <!-- bootstrap wysihtml5 - text editor -->
        <link rel="stylesheet" href="{% static 'assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.css'%}">


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- google font -->
        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    </head>
    <body>
    <div class="wrapper">
        <div class="content-wrapper">
            <section class="content">
                <div class="candidate-register">
                    <div class="col-xl-6 col-lg-12">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title" style="display: flex;justify-content: center">Message</h3>
                            </div>
                            <div class="box-body">
                                <div class="form-group">
                                    <p>An Activation Link has been send to you at your email.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

            <!-- jQuery 3 -->
        <script src="{% static 'assets/vendor_components/jquery/dist/jquery-3.3.1.js' %}"></script>

        <!-- jQuery UI 1.11.4 -->
        <script src="{% static 'assets/vendor_components/jquery-ui/jquery-ui.js' %}"></script>

        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
          $.widget.bridge('uibutton', $.ui.button);
        </script>

        <!-- popper -->
        <script src="{% static 'assets/vendor_components/popper/dist/popper.min.js' %}"></script>

        <!-- Bootstrap v4.1.3.stable -->
        <script src="{% static 'assets/vendor_components/bootstrap/dist/js/bootstrap.js' %}"></script>

        <!-- Morris.js charts -->
        <script src="{% static 'assets/vendor_components/raphael/raphael.js' %}"></script>
        <script src="{% static 'assets/vendor_components/morris.js/morris.js' %}"></script>

        <!-- Sparkline -->
        <script src="{% static 'assets/vendor_components/jquery-sparkline/dist/jquery.sparkline.js' %}"></script>

        <!-- jvectormap -->
        <script src="{% static 'assets/vendor_plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
        <script src="{% static 'assets/vendor_plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>

        <!-- jQuery Knob Chart -->
        <script src="{% static 'assets/vendor_components/jquery-knob/js/jquery.knob.js' %}"></script>

        <!-- daterangepicker -->
        <script src="{% static 'assets/vendor_components/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'assets/vendor_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

        <!-- datepicker -->
        <script src="{% static 'assets/vendor_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.js' %}"></script>

        <!-- Bootstrap WYSIHTML5 -->
        <script src="{% static 'assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js' %}"></script>

        <!-- Slimscroll -->
        <script src="{% static 'assets/vendor_components/jquery-slimscroll/jquery.slimscroll.js' %}"></script>

        <!-- FastClick -->
        <script src="{% static 'assets/vendor_components/fastclick/lib/fastclick.js' %}"></script>

        <!-- maximum_admin App -->
        <script src="{% static 'js/template.js' %}"></script>

        <!-- maximum_admin dashboard demo (This is only for demo purposes) -->
        <script src="{% static 'js/pages/dashboard.js' %}"></script>

        <!-- maximum_admin for demo purposes -->
        <script src="{% static 'js/demo.js' %}"></script>
    </body>
</html>

bidcruit/candidate/templates/candidate/landing-index.html
{% load static %}
<!doctype html>
<html lang="en" dir="ltr">

<head>

	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
	<meta content="Responsive Bootstrap 4 Dashboard Template" name="description">
	<meta content="BootstrapDash" name="author">
	<title>BidCruit Home</title>

	<!-- favicon -->
	<link rel="icon" href="{% static 'assets/img/brand/bluelogo.png' %}" type="image/x-icon" />

	<!-- Icons css -->
	<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">

	<!-- Bootstrap css -->
	<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">

	<!-- Style css -->
	<link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/style.css' %}">

	<!-- Colors css -->
	<!-- <link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/colors/color.css' %}"> -->

	<!--- Map css --->
	<!-- <link href="{% static 'assets/plugins/jqvmap/jqvmap.min.css' %}" rel="stylesheet"> -->

	<!-- Owl-carousel css-->
	<link href="{% static 'assets/plugins/owl-carousel/owl.carousel.css' %}" rel="stylesheet" />

	<!-- Sidemenu css -->
	<link rel="stylesheet" href="{% static 'assets/css/single-sidemenu/singlemenu.css' %}">




	<!-- Internal Spectrum-colorpicker css -->
	<!-- <link href="{% static 'assets/plugins/spectrum-colorpicker/spectrum.css' %}" rel="stylesheet"> -->

	<!-- Sidebar css -->
	<!-- <link href="{% static 'assets/plugins/sidebar/sidebar.css' %}" rel="stylesheet"> -->

	<!-- Internal Fileupload css -->
	<link href="{% static 'assets/plugins/fileuploads/css/fileupload.css' %}" rel="stylesheet" type="text/css" />

	<!-- Skinmodes css -->
	<!-- <link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet"> -->

	<!-- Darktheme css -->
	<!-- <link href="{% static 'assets/css/style-dark.css' %}" rel="stylesheet"> -->

	<!-- Internal Fileupload css -->
	<!-- <link href="{% static 'assets/plugins/fileuploads/css/fileupload.css' %}" rel="stylesheet" type="text/css"/> -->

	<!-- Animations css -->
	<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
	<!-- Select2 css -->
	<link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet">
	<link
		href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,700;0,800;0,900;1,600&display=swap"
		rel="stylesheet">
	<!-- Candidateprofile css -->
	<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
</head>

<body>
	<div class="lending-wrapper">
		<header class="landing-header">
			<div class="container">
				<div class="row">
					<div class="col-lg-2 col-md-3 col-sm-6 col-xs-6">
						<div class="logo">
							<a href="" title=""><img src="{% static 'assets/img/brand/logo.png' %}" alt="Logo" title=""></a>
						</div>
					</div>
					<div class="col-lg-10 col-md-9 col-sm-6 col-xs-6">
						<div class="custom-navbar">
							<nav class="navbar navbar-expand-lg navbar-light">
								<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
									<span class="navbar-toggler-icon"><i data-v-e08301e8="" class="fas fa-align-justify"></i></span>
								  </button>
								<div class="collapse navbar-collapse" id="navbarSupportedContent">
								  <ul class="navbar-nav ml-auto">
									<li class="nav-item active">
									  <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
									</li>
									<li class="nav-item">
									  <a class="nav-link" href="#">Contact</a>
									</li>
									<li class="nav-item dropdown">
									  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Register
									  </a>
									  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
										<a class="dropdown-item" href="{% url 'candidate:signup' %}">Candidate Register</a>
										<a class="dropdown-item" href="{% url 'company:signup' %}">Company Register</a>
<!--										<div class="dropdown-divider"></div>-->
<!--										<a class="dropdown-item" href="#">Something else here</a>-->
									  </div>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'accounts:signin' %}">Login</a>
									</li>
								
								  </ul>
								 
								</div>
							  </nav>
							
						</div>
					</div>
				</div>
			</div>
		</header>
		<main class="landing-bg">
			<section class="landing-detail">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<p>Find Jobs,Employment & Career Opportunities</p>
							<h1>Drop Resume & Get <br>Your Desire Job !</h1>
		
							<div class="search-here">
								<div class="row">
									<div class="col-lg-5 col-md-6 col-sm-12 col-xs-12">
										<div class="custom-select-ser">
											<span class="ad-icon-select"><i data-v-e08301e8="" class="fas fa-search"></i></span>
											<select class="form-control select2 " data-placeholder="Job Title, Keyword, Company">
												<option value="Firefox">
													Job Title, Keyword, Company
												</option>
												<option value="Chrome">
													Chrome
												</option>
												<option value="Safari">
													Safari
												</option>
												<option value="Opera">
													Opera
												</option>
												<option value="Internet Explorer">
													Internet Explorer
												</option>
											</select>
										</div>
										
									</div>
									<div class="col-lg-5 col-md-6 col-sm-12 col-xs-12">
										<div class="custom-select-ser">
											<span class="ad-icon-select"><i data-v-e08301e8="" class="fas fa-map-marker-alt"></i></span>
											<select class="form-control select2" data-placeholder="City Or Post code">
												<option value="Firefox">
													City Or Post code
												</option>
												<option value="Chrome">
													Chrome
												</option>
												<option value="Safari">
													Safari
												</option>
												<option value="Opera">
													Opera
												</option>
												<option value="Internet Explorer">
													Internet Explorer
												</option>
											</select>
										</div>
									</div>
									<div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
										<div class="search-btn">
											<button class="custom-button">Search</button>
										</div>
									</div>
									<div class="last-de">
										<a title="#" href="">Fill Job <strong>Application</strong> now !</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</section>
		</main>
	</div>

	<!-- Back-to-top -->
	<a href="#top" id="back-to-top"><i class="ti-angle-double-up"></i></a>
	<!-- JQuery min js -->
	<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
	<!-- Jquery.steps js -->
	<script src="{% static 'assets/plugins/jquery-steps/build/jquery.steps.min.js' %}"></script>
	<script src="{% static 'assets/plugins/parsleyjs/parsley.min.js' %}"></script>
	<!--- Form-wizard js --->
	<script src="{% static 'assets/js/form-wizard.js' %}"></script>
	<!-- Popper js -->
	<script src="{% static 'assets/plugins/popper/popper.min.js' %}"></script>
	<!-- Datepicker js -->
	<script src="{% static 'assets/plugins/jquery-ui/ui/widgets/datepicker.js' %}"></script>
	<!-- Bootstrap Bundle js -->
	<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- Internal jquery.maskedinput js -->
	<script src="{% static 'assets/plugins/jquery.maskedinput/jquery.maskedinput.js' %}"></script>
	<!-- Internal Spectrum-colorpicker js -->
	<script src="{% static 'assets/plugins/spectrum-colorpicker/spectrum.js' %}"></script>
	<!-- Select2.min js -->
	<script src="{% static 'assets/plugins/select2/js/select2.min.js' %}"></script>
	<!-- Internal ion.rangeSlider.min js -->
	<!-- <script src="{% static 'assets/plugins/ion-rangeslider/js/ion.rangeSlider.min.js' %}"></script> -->

	<!-- Ionicons js -->

	<!-- Rating js -->
	<!-- <script src="{% static 'assets/plugins/rating/jquery.rating-stars.js' %}"></script>
		<script src="{% static 'assets/plugins/rating/jquery.barrating.js' %}"></script> -->
	<!-- P-scroll js -->
	<!-- <script src="{% static 'assets/plugins/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
	<script src="{% static 'assets/plugins/perfect-scrollbar/p-scroll.js' %}"></script> -->
	<!-- Sidemenu js -->
	<!-- <script src="{% static 'assets/plugins/side-menu/single-menu.js' %}"></script> -->
	<!-- Right-sidebar js -->
	<!-- <script src="{% static 'assets/plugins/sidebar/sidebar.js' %}"></script> -->
	<!-- <script src="{% static 'assets/plugins/sidebar/sidebar-custom.js' %}"></script> -->
	<!-- form-elements js -->
	<script src="{% static 'assets/js/form-elements.js' %}"></script>

	<!-- Custom js -->
	<script src="{% static 'assets/js/custom.js' %}"></script>



</body>

</html>