bidcruit/bidcruit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from candidate import views
from accounts import views as account_views
from candidate import views as candidate_views
from company import views as company_view
handler404 = 'accounts.views.handler404'
handler500 = 'accounts.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidate.urls')),
    path('agency/', include('agency.urls')),
    path('', account_views.bidcruit_home, name='bidcruit_home'),
    path('company/', include('company.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path("password_reset", auth_views.PasswordResetView.as_view(template_name='candidate/password/password_reset.html',
                                                                html_email_template_name='candidate/password/password_reset_email.html'),
         name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='candidate/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="candidate/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='candidate/password/password_reset_complete.html'),
         name='password_reset_complete'),
    path('tinymce/', include('tinymce.urls')),
    path('<str:url>/', candidate_views.timeline, name="timeline"),
    path('view_job/<int:id>',company_view.view_job,name="view_job"),
    path('apply_job/<int:id>/',candidate_views.apply_job,name='apply_job'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bidcruit/candidate/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'candidate'

urlpatterns = [
    path('home/', views.index, name='home'),
    path('signup', views.ragister, name="signup"),
    path('signup/<str:referral>', views.referral_signup, name="referral_signup"),
    url(r'^country/(?P<id>\d+)/$', views.state_view),
    url(r'^state/(?P<id>\d+)/$', views.city_view),
    url(r'^cities_by_country/(?P<id>\d+)/$', views.cities_by_country),
    url(r'^preference_cities_by_country/(?P<id>\d+)/$', views.preference_cities_by_country),
    path('candidate_profile', views.candidate_profile, name="candidate_profile"),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    path('/<str:url>/', views.timeline, name="timeline"),
   
    # charts
    path('statistics/', views.statistics_view, name="candidate_statistics"),
    path('chart/filter-options/', views.get_filter_options, name='chart-filter-options'),
    path('chart/payment-method/', views.payment_method_chart, name='chart-payment-method'),
    path('chart/job-experience/', views.job_exp_Chart, name='chart-job-experience'),
    path('chart/edu-percentage/', views.edu_per_chart, name='chart-edu-percentage'),
    path('charts', views.charts, name='charts'),


    # Wizard
    path('upload_resume/personal_detail_temp', views.personal_detail_temp, name="personal_detail_temp"),
    path('upload_resume/education_temp', views.education_temp, name="education_temp"),
    path('upload_resume/work_experience_temp', views.work_experience_temp, name="work_experience_temp"),
    path('upload_resume/skill_temp', views.skill_temp, name="skill_temp"),
    path('upload_resume/other_temp', views.other_temp, name="other_temp"),
    path('upload_resume/remove_record', views.remove_record, name="remove_record"),
    path('upload_resume/save_resume', views.save_resume, name="save_resume"),
    path('create_resume_pass/', views.create_resume_pass, name="create_resume_pass"),
    path('update_resume_pass/', views.update_resume_pass, name="update_resume_pass"),
    path('update_share_url/',views.update_share_url,name="update_share_url"),
    path('check_sharing_url_is_valid',views.check_sharing_url_is_valid,name="check_sharing_url_is_valid"),

    # Dashboard
    path('upload_resume_add/<str:url>', views.upload_resume, name='upload_resume_add'),
    path('add_profile/',views.add_profile,name='add_profile'),
    path('add_profile_detail/<str:url>',views.add_profile_detail,name='add_profile_detail'),
    path('toggle_profile/', views.toggle_profile, name="toggle_profile"),
    path('toggle_field_state/', views.toggle_field_state, name="toggle_field_state"),
    path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('job_preference/', views.candidate_job_preference, name="job_preference"),

    #  Request
    path('hire_request/', views.hire_request, name="hire_request"),
    path('accept_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.accept_request, name="accept_request"),
    path('reject_request/<str:profile_id>/<int:company_id>/<str:hire_id>', views.reject_request, name="reject_request"),
    path('data_accept_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_accept_request, name="data_accept_request"),
    path('data_reject_request/<str:profile_id>/<int:company_id>/<str:data_id>/', views.data_reject_request, name="data_reject_request"),

    path('file_download',views.file_download,name="file_download"),
    path('look_for_job_check/', views.look_for_job_check, name="look_for_job_check"),
    path('delete_exp_document', views.delete_exp_doc, name="delete_exp_doc"),
    path('candidate_resume_update/', views.candidate_resume_update, name="candidate_resume_update"),

    # Profile update
    # path('edit_profile/<str:profile_id>', views.edit_profile, name="edit_profile"),
    path('download_folder/<int:candidate_id>/',views.download_folder,name="download_folder"),
    path('test_redirect/', views.test_redirect, name="test_redirect"),


    #apply job
    path('add_apply_candidate/', views.add_apply_candidate, name='add_apply_candidate'),
    path('applied_job_list/', views.applied_job_list, name='applied_job_list'),
    path('candidate_jcr/<int:id>/<int:job_id>', views.candidate_jcr, name='candidate_jcr'),
    path('applied_job_detail/<int:id>', views.applied_job_detail, name='applied_job_detail'),
    path("prequisites_view/<int:id>/<int:job_id>", views.prequisites_view, name="prequisites_view"),

]

bidcruit/chat/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
app_name= 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("chat/<str:email>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

bidcruit/candidate/views.py
import os
import shutil
from django.contrib.auth.forms import PasswordResetForm
from bidcruit import settings
import re
from elasticsearch_dsl import Q as Elastic_Q
from company.documents import CandidateDocument
import json
import random
import string
from datetime import datetime
from dateutil.relativedelta import relativedelta
import datetime
from rest_framework.response import Response
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from accounts.tokens import account_activation_token
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from django.contrib.auth.decorators import login_required
from . import models
import pyotp
import re
from accounts.views import activate_account_confirmation
import socket
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, request
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from .utils.charts import months, colorPrimary, colorSuccess, colorDanger, generate_color_palette, get_year_dict
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
)
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from rest_framework.decorators import api_view
from django.http.response import JsonResponse
import pyqrcode
from company.models import CandidateHire, CompanyProfile, JCR, JobCreation, AppliedCandidate,JobWorkflow,WorkflowStages,PreRequisites,Template_creation
import png
from pyqrcode import QRCode
import qrcode
from io import BytesIO
from django.core.files import File
import pandas as pd
from chat.models import Messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.hashers import check_password
import candidate
from io import BytesIO
import zipfile

User = get_user_model()
cureent_user = False
from django.core import serializers


def bidcruit_home(request):
    return render(request, 'candidate/landing-index.html')


def state_view(request, id):
    states = models.State.objects.filter(country_code_id=id)
    context = {"states": states}
    return render(request, "candidate/state.html", context)


#  to populate city dropdown when state is selected.
def city_view(request, id):
    cities = models.City.objects.filter(state_code_id=id)
    if cities:
        context = {"cities": cities}
    else:
        context = {"cities": ["", 0]}
    return render(request, "candidate/city.html", context)


# get all cities of selected country
def cities_by_country(request, id):
    states = models.State.objects.filter(country_code=id).values_list('id')
    cities = models.City.objects.filter(state_code_id__in=states)
    if cities:
        context = {"cities": cities}
    else:
        context = {"cities": ["", 0]}
    return render(request, "candidate/city.html", context)


def preference_cities_by_country(request, id):
    states = models.State.objects.filter(country_code=id).values_list('id')
    cities = models.City.objects.filter(state_code_id__in=states)
    if cities:
        context = {"cities": cities}
    else:
        context = {"cities": ["", 0]}
    return render(request, "candidate/preference_city.html", context)


@login_required(login_url="/")
def get_active_profile(userid):
    profiles = models.Profile.objects.filter(candidate_id=User.objects.get(id=userid))
    for i in profiles:
        if i.active == True:
            # candidate_profile = models.CandidateProfile.objects.get(profile_id=i)
            return i


def get_present_year():
    return int(datetime.datetime.now().year)


def get_present_month():
    return datetime.datetime.now().strftime('%B')


@login_required(login_url="/")
def index(request):
    if request.user.is_candidate:
        context = {}
        if models.CandidateSEO.objects.filter(candidate_id=request.user.id).exists():
            context['seo'] = models.CandidateSEO.objects.get(candidate_id=request.user.id)
        current_user = models.CandidateProfile.objects.filter(candidate_id=request.user.id).first()
        get_all_profile = models.CandidateProfile.objects.filter(candidate_id=request.user.id)
        get_profile_list = [i.profile_id.id for i in get_all_profile]
        models.Profile.objects.filter(candidate_id=request.user.id).exclude(id__in=get_profile_list).delete()
        referral_list = models.ReferralDetails.objects.filter(referred_by=User.objects.get(id=request.user.id))
        count = 0
        profiles = models.Profile.objects.filter(candidate_id=request.user.id)
        profile_count = len(profiles)
        for i in profiles:
            if i.active == True:
                # print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>",i.id)
                request.session['active_profile_id'] = i.id
                context['active_profile_hide_fields'] = models.Candidate_Hide_Fields.objects.get(
                    candidate_id=request.user, profile_id=i)
                context['active_profile'] = i
                context['userdata'] = models.CandidateProfile.objects.get(candidate_id=request.user, profile_id=i)
                break
        for i in referral_list:
            if i.referred_to.is_active:
                count += 1
        if models.CandidateSEO.objects.filter(candidate_id=request.user.id).exists():
            context['seo'] = models.CandidateSEO.objects.get(candidate_id=request.user.id)
        context['profile'] = current_user
        context['get_all_profile'] = get_all_profile
        context['referral_list'] = referral_list
        context['count'] = count
        context['profiles'] = profiles
        context['profile_count'] = profile_count
    else:
        return redirect('accounts:user_logout')
    return render(request, 'candidate/Dashbord-profile.html', context)


def generate_referral_code():
    num = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(12)])
    return num


def ragister(request):
    alert = {}
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fname = request.POST.get('fname')
            lname = request.POST.get('lname')
            email = request.POST.get('email')
            referred_by = request.POST.get('referral_code')
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')
            checkbox = request.POST.get('checkbox')
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            device_type = ""
            if request.user_agent.is_mobile:
                device_type = "Mobile"
            if request.user_agent.is_tablet:
                device_type = "Tablet"
            if request.user_agent.is_pc:
                device_type = "PC"
            browser_type = request.user_agent.browser.family
            browser_version = request.user_agent.browser.version_string
            os_type = request.user_agent.os.family
            os_version = request.user_agent.os.version_string
            context1 = {
                "ip": ip,
                "device_type": device_type,
                "browser_type": browser_type,
                "browser_version": browser_version,
                "os_type": os_type,
                "os_version": os_version
            }
            if User.objects.filter(email=request.POST['email']).exists():
                alert['message'] = "email already exists"
            else:
                usr = User.objects.create_candidate(email=email, first_name=fname, last_name=lname,
                                                    password=password, ip=ip, device_type=device_type,
                                                    browser_type=browser_type,
                                                    browser_version=browser_version, os_type=os_type,
                                                    os_version=os_version,
                                                    referral_number=generate_referral_code(), referred_by=referred_by)
                try:
                    mail_subject = 'Activate your account.'
                    current_site = get_current_site(request)
                    # print('domain----===========',current_site.domain)
                    html_content = render_to_string('accounts/acc_active_email.html', {'user': usr,
                                                                                       'name': fname + ' ' + lname,
                                                                                       'email': email,
                                                                                       'domain': current_site.domain,
                                                                                       'uid': urlsafe_base64_encode(
                                                                                           force_bytes(usr.pk)),
                                                                                       'token': account_activation_token.make_token(
                                                                                           usr), })
                    to_email = usr.email
                    from_email = settings.EMAIL_HOST_USER
                    msg = EmailMultiAlternatives(mail_subject, mail_subject, from_email, to=[to_email])
                    msg.attach_alternative(html_content, "text/html")
                    msg.send()
                    if models.User.objects.filter(referral_number=referred_by).exists():

bidcruit/candidate/templates/candidate/ATS/candidate_applied_job.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for job in applied_job %}
    <a href="{% url 'candidate:applied_job_detail' job.job_id %}"><h1>{{job.job_id.job_title}}</h1></a>
{% endfor %}

</body>
</html>

bidcruit/candidate/templates/candidate/ATS/candidate_applied_job_detail_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>{{job_obj.job_title}}</h2><br>
{% for stage in workflow_stages %}
        {% ifequal stage.stage.name 'JCR' %}
           {{stage.stage.name}} <a href="{% url 'candidate:candidate_jcr' stage.template.id job_obj.id %}"><button >Submit</button></a><hr>
        {% endifequal %}
        {% ifequal stage.stage.name 'Prerequisites' %}
           {{stage.stage.name}} <a href="{% url 'candidate:prequisites_view' stage.template.id job_obj.id %}"><button >Submit</button></a><hr>
        {% endifequal %}
{% endfor %}
</body>
</html>

bidcruit/candidate/templates/candidate/ATS/jcr_candidate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="Description" content="">
		<meta name="Author" content="">
		<meta name="Keywords" content=""/>

		<!-- Title -->
		<title>  </title>

		<!-- Favicon -->
		<link rel="icon" href="{% static 'assets/img/brand/favicon.png' %}" type="image/x-icon"/>

		<!-- Icons css -->
		<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">

		<!-- Bootstrap css -->
		<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">

		<!-- Right-sidemenu css -->
		<link href="{% static 'assets/plugins/sidebar/sidebar.css' %}" rel="stylesheet">

		<!-- Style css -->
		<link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/style.css' %}">

		<!-- Colors css -->
		<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/colors/color.css' %}">

		<!-- Skinmodes css -->
		<link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet">

		<!-- Darktheme css -->
		<link href="{% static 'assets/css/style-dark.css' %}" rel="stylesheet">

		<!-- Sidemenu css -->
		<link rel="stylesheet" href="{% static 'assets/css/single-sidemenu/singlemenu.css' %}">

		<!-- Internal Nice-select css  -->
		<link href="{% static 'assets/plugins/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet"/>

		<!-- Animations css -->
		<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
		
		<link href="{% static 'assets/css/ATS/jcr_candidate.css' %}" rel="stylesheet">

	</head>

	<body class="main-body app sidebar-mini sidenav-toggled">

		<!-- Page -->
		<div class="page">
			<!-- main-sidebar -->

			<!-- Main-content -->

		    <div class="apply_job_main_header">
				<div class="apply_job_main_content">
					<img src="{% static 'assets/img/ATS/logo.png' %}">
				</div>
		    </div>

			<div class="main-content-jcr">				
               
				<div class="container-fluid">
					<div class="card mg-b-15">
						<div class="card-body">
							<div class="cardheader pr-0">
								<div class="media">
									
									<div class="media-body name_skils_title">
										<div class="apply_job_info_view">

											<div class="company_profile_logo"><img src="img/tata_logo.png' %}"></div>
											<div class="name_dev">
												<h1 class="mb-0 mg-t-0 name">{{job_obj.job_title}}</h1>
												<span class="text-muted">{{job_obj.company_id.company_name}}</span>
									    	</div>

											<div class="media mg-t-10 profile_applyjob">
												<div class="applyjob_profile_footer">
													<div class="applyjob_profile_title"><i class="fas fa-industry"></i> Industry :-</div>
													<div class="applyjob_profilevalue">{{job_obj.industry_type.name}}</div>
												</div>
												<div class="applyjob_profile_footer">
													<div class="applyjob_profile_title"><i class="fas fa-dollar-sign"></i> Salary :-</div>
													<div class="applyjob_profilevalue">{{job_obj.max_salary}}</div>
												</div>
												<div class="applyjob_profile_footer">
													<div class="applyjob_profile_title"><i class="fas fa-tv"></i> Experience :-</div>
													<div class="applyjob_profilevalue">{{job_obj.experience_year}} years {{job_obj.experience_month}} month</div>
												</div>
												<div class="applyjob_profile_footer">
													<div class="applyjob_profile_title"><i class="fas fa-laptop-medical"></i> Remote Job :-</div>
													<div class="applyjob_profilevalue">{% if job_obj.remote_job %} Yes {% else %} No {% endif %}</div>
												</div>	
											</div>
										</div>
									</div>
									
								</div>
							</div>						
							
						</div>
						
					</div>
				</div>`
				<!-- Container-fluid add-candidate layout-->
				<div class="container-fluid">

					<!-- Maincontentbody -->
					<div class="maincontentbody">

						

						<!-- row add new candidate layout-->
						<div class="row add-candidate-layout" id="">
							<div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
								<!--div-->
								<form method="POST">
									{% csrf_token %}
									<div class="card">
										<div class="card-body">

											<div class="job_compatibility card-header pb-0">
												<div class="d-flex justify-content-between">
													<h4 class="card-title mg-b-0">please fill skills details for job compatibility</h4>
													<div class="candidate_right_filters_section">
														<div class="candidate_view_header">
															<a class="btn btn-quit btn-block" href="#">Quit</a>
														</div>
													</div>
												</div>
											</div>

											<div class="Question_listing">
												{% for i in getStoreData %}
													{% for j in i.addDetailsItem %}
														{% for k in j.cat_subtype %}
															<div class="question_listing_inner">
<!--																<div class="question_listing_count">Question 1</div>-->
																<div class="question_text">{{k.question}}.</div>
																<div class="question_option_box">
																	{% ifequal k.matching 'multi' %}
																		<div class="radio-group gender-select mg-t-10">
																			{% for l in k.details %}
																			<div class="option_tab_q">
																				<label class="ckbox_q">
																					<input name="{{k.id}}" required type="checkbox" value="{{l.title}}"><span>{{l.title}}</span>

																				</label>
																			</div>
																			 {% endfor %}
																		</div>
																	{% endifequal %}
																	{% ifequal k.matching 'single' %}
																		{% for l in k.details %}
																			<div class="option_tab_q">
																				<label class="rdiobox">
																					<input name="{{k.id}}" required type="radio" value="{{l.title}}" data-parsley-multiple="basic_radio"><span>{{l.title}}</span>
																				</label>
																			</div>
																		{% endfor %}
																	{% endifequal %}
																</div>
															</div>
												 		{% endfor %}
													{% endfor %}
												{% endfor %}
											</div>

											<div class="QuestionSubmit_btn">
												<button class="btn btn-sm btn-primary QuestionSubmit btn-sm btn-rounded" type="submit">Submit</button>
											</div>
										</div>
									</div>
								</form>
							</div>
							
						</div>
						<!-- /row -->
					</div>
					<!-- Main-content-body closed -->
				</div>
				<!-- Container-fluid add-candidate layout closed -->



			</div>
			<!-- Main-content closed -->

			<!-- Footer opened -->
			<div class="main-footer ht-40">
				<div class="container-fluid pd-t-0-f ht-100p">
					<span>Copyright &copy; 2020 <a href="#">Admix</a>. Designed by <a href="https://www.spruko.com/">Spruko</a> All rights reserved.</span>
				</div>
			</div>
			<!-- Footer closed -->

		</div>
		<!-- Page closed -->

        <!-- Back-to-top -->
		<a href="#top" id="back-to-top"><i class="las la-angle-double-up"></i></a>

		<!-- JQuery min js -->
		<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

		<!-- Popper js -->
		<script src="{% static 'assets/plugins/popper/popper.min.js' %}"></script>

		<!-- Bootstrap Bundle js -->
		<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

		<!-- Ionicons js -->
		<script src="{% static 'assets/plugins/ionicons/ionicons.js' %}"></script>

		<!-- Moment js -->
		<script src="{% static 'assets/plugins/moment/moment.js' %}"></script>

		<!-- JQuery sparkline js -->
		<script src="{% static 'assets/plugins/jquery-sparkline/jquery.sparkline.min.js' %}"></script>

		
		<!-- Rating js -->
		<script src="{% static 'assets/plugins/rating/jquery.rating-stars.js' %}"></script>
		<script src="{% static 'assets/plugins/rating/jquery.barrating.js' %}"></script>

		
		<!-- Right-sidebar js -->
		<script src="{% static 'assets/plugins/sidebar/sidebar-custom.js' %}"></script>

		<!-- Internal Nice-select js-->
		<script src="{% static 'assets/plugins/jquery-nice-select/js/jquery.nice-select.js' %}"></script>
		<script src="{% static 'assets/plugins/jquery-nice-select/js/nice-select.js' %}"></script>

		<!-- Custom js -->
		<script src="{% static 'assets/js/custom.js' %}"></script>
		<script>
			var requiredCheckboxes = $(':checkbox[required]');
			  requiredCheckboxes.on('change', function(e) {
				var checkboxGroup = requiredCheckboxes.filter('[name="' + $(this).attr('name') + '"]');
				var isChecked = checkboxGroup.is(':checked');
				checkboxGroup.prop('required', !isChecked);
			  });
			  requiredCheckboxes.trigger('change');
		</script>
	</body>
</html>