bidcruit/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'accounts'

urlpatterns = [
    path('resend_otp/', views.resend_otp, name="resend_otp"),
    url(r'^user_login_password/$', views.user_login_password, name='user_login_password'),
    url(r'^$', views.user_login_email, name='signin'),
    url(r'^verify_otp/$', views.verify_otp, name='verify_otp'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    path('check_email_is_valid', views.check_email_is_valid, name="check_email_is_valid"),
    url(r'^activate/('
        r'?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    # url(r'^activate_account_confirmation/$', views.activate_account_confirmation, name='activate_account_confirmation'),
    path('back_to_home',views.back_to_home,name='back_to_home'),

    #ATS
    path('apply_job_cadidate_sendotp',views.apply_job_cadidate_sendotp,name='apply_job_cadidate_sendotp'),
    path('job_apply_verify_otp',views.job_apply_verify_otp,name='job_apply_verify_otp'),

    
]

bidcruit/agency/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name= 'agency'

urlpatterns = [
    path('agency_registration', views.agency_registration, name="agency_registration"),
    path('agency_home', views.agency_home, name="agency_home"),
]

bidcruit/bidcruit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from candidate import views
from accounts import views as account_views
from candidate import views as candidate_views
from company import views as company_view
handler404 = 'accounts.views.handler404'
handler500 = 'accounts.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('candidate/', include('candidate.urls')),
    path('agency/', include('agency.urls')),
    path('', account_views.bidcruit_home, name='bidcruit_home'),
    path('company/', include('company.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path("password_reset", auth_views.PasswordResetView.as_view(template_name='candidate/password/password_reset.html',
                                                                html_email_template_name='candidate/password/password_reset_email.html'),
         name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='candidate/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="candidate/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='candidate/password/password_reset_complete.html'),
         name='password_reset_complete'),
    path('tinymce/', include('tinymce.urls')),
    path('<str:url>/', candidate_views.timeline, name="timeline"),
    path('view_job/<int:id>',company_view.view_job,name="view_job"),
    path('apply_job/<int:id>/',candidate_views.apply_job,name='apply_job'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bidcruit/chat/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
app_name= 'chat'

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("chat/<str:email>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]

bidcruit/agency/models.py
from django.db import models

# Create your models here.

bidcruit/agency/views.py
from bidcruit import settings
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from accounts.tokens import account_activation_token
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from . import models
from accounts.views import activate_account_confirmation
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, request
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.encoding import force_bytes
from company.models import CandidateHire, CompanyProfile
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
)
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
User = get_user_model()
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from smtplib import SMTPException

# Create your views here.


def agency_registration(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            fname = request.POST.get('fname')
            lname = request.POST.get('lname')
            email = request.POST.get('email')
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')
            checkbox = request.POST.get('checkbox')
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            device_type = ""
            if request.user_agent.is_mobile:
                device_type = "Mobile"
            if request.user_agent.is_tablet:
                device_type = "Tablet"
            if request.user_agent.is_pc:
                device_type = "PC"
            browser_type = request.user_agent.browser.family
            browser_version = request.user_agent.browser.version_string
            os_type = request.user_agent.os.family
            os_version = request.user_agent.os.version_string
            if User.objects.filter(email=request.POST['email']).exists():
                messages.error(request, 'User Already Exists.')
                return render(request, 'agency/agency_registration.html')
            else:
                usr = User.objects.create_agency(first_name=fname, last_name=lname,email=email,password=password,
                                                 ip=ip, device_type=device_type,browser_type=browser_type,
                                                 browser_version=browser_version, os_type=os_type,os_version=os_version)
                mail_subject = 'Activate your account.'
                current_site = get_current_site(request)
                html_content = render_to_string('accounts/acc_active_email.html', {'user': usr,
                                                                                   'name': fname + ' ' + lname,
                                                                                   'email': email,
                                                                                   'domain': current_site.domain,
                                                                                   'uid': urlsafe_base64_encode(
                                                                                       force_bytes(usr.pk)),
                                                                                   'token': account_activation_token.make_token(
                                                                                       usr), })
                to_email = usr.email
                from_email = settings.EMAIL_HOST_USER
                msg = EmailMultiAlternatives(mail_subject, mail_subject, from_email, to=[to_email])
                msg.attach_alternative(html_content, "text/html")
                try:
                    msg.send()
                except BadHeaderError:
                    User.objects.get(email__exact=email).delete()
                    messages.error(request, 'Invalid header found.')
                    return render(request, 'agency/agency_registration.html')
                except SMTPException as e:
                    User.objects.get(email__exact=email).delete()
                    messages.error(request, e)
                    return render(request, 'agency/agency_registration.html')
                except:
                    User.objects.get(email__exact=email).delete()
                    messages.error(request, 'Mail sending failed, Please check your internet connection !!')
                    return render(request, 'agency/agency_registration.html')
                return activate_account_confirmation(request, fname + ' ' + lname, email)
    else:
        if request.user.is_authenticated:
            if request.user.is_candidate:
                return redirect('candidate:home')
            if request.user.is_company:
                profile = CompanyProfile.objects.filter(company_id=request.user.id)
                if profile:
                    return redirect('company:company_profile')
                else:
                    return redirect('company:add_edit_profile')
    return render(request, 'agency/agency_registration.html')


@login_required(login_url="/")
def agency_home(request):
    return render(request, 'agency/agency_home.html')

bidcruit/agency/templates/agency/agency_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <center><h1>Agency Logged In</h1></center>
        <h5>Welcome To Bidcruit</h5><br><br>
        <a href="{% url 'accounts:user_logout' %}">Logout</a>
    </div>
</body>
</html>

bidcruit/agency/templates/agency/agency_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="UTF-8">
		<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="Description" content="">
		<meta name="Author" content="">
		<meta name="Keywords" content=""/>

		<!-- Title -->
		<title> Agency Registration </title>

		<!-- Favicon -->
		<link rel="icon" href="{% static 'assets/img/brand/bluelogo.png' %}" type="image/x-icon"/>

		<!-- Icons css -->
		<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet">

		<!-- Bootstrap css -->
		<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">

		<!-- Right-sidemenu css -->
		<link href="{% static 'assets/plugins/sidebar/sidebar.css' %}" rel="stylesheet">

		<!-- Style css -->
		<link rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/style.css' %}">

		<!-- Colors css -->
		<link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'assets/css/colors/color.css' %}">

		<!-- Skinmodes css -->
		<link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet">

		<!-- Darktheme css -->
		<link href="{% static 'assets/css/style-dark.css' %}" rel="stylesheet">

		<!-- Sidemenu css -->
		<link rel="stylesheet" href="{% static 'assets/css/sidemenu/sidemenu.css' %}">

		<!-- Animations css -->
		<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">

		<!-- cadidate profile css -->
		<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">

	</head>
	<body class="main-body">

	<!-- Page -->
		<div class="page">

		<!-- Loader -->
		<div id="global-loader">
			<img src="{% static 'assets/img/loader.svg' %}" class="loader-img" alt="Loader">
		</div>
		<!-- /Loader -->
		<div class="container-fluid">
			{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
			<div class="row no-gutter">
				<!-- The image half -->
				<div class="col-md-6 col-lg-6 col-xl-7 d-md-flex bg-image d-logo-center">
					<div class="row">
						<div class="col-md-10 col-lg-10 col-xl-8 my-auto mx-auto">
								<div class="logo-bg">
								<div class="d-flex">
									<a href="{% url 'bidcruit_home' %}">
                                        <img src="{% static 'assets/img/brand/bluelogo.png' %}" class="sign-fav" alt="logo">
                                    </a>
                                    <h1 class="main-logo1 ml-1 mr-0 my-auto tx-28 text-white bl-size"><span>BidCruit</span></h1>
								  </div>
							</div>
						</div>
					</div>
				</div>
				<!-- The content half -->
				<div class="col-md-6 col-lg-6 col-xl-5 bg-white">
					<div class="login d-flex align-items-center py-2">
						<!-- Demo content-->
						<div class="container p-0">
							<div class="row">
								<div class="col-md-10 col-lg-10 col-xl-9 mx-auto">
									<div class="card-sigin">
										<div class="main-signup-header">
											<h2 class="text-primary">Get Started</h2>
											<h5 class="font-weight-normal mb-4">It's free to signup and only takes a minute.</h5>
											<form method="POST" name="agency_register" id="agency_register">
												{% csrf_token %}
												<div class="row">
													<div class="col-md-6">
														<div class="form-group">
															<label>First Name</label> <input class="form-control" placeholder="Enter your first name" type="text" name="fname">
														</div>
													</div>
													<div class="col-md-6">
														<div class="form-group">
															<label>Last Name</label> <input class="form-control" placeholder="Enter your last name" type="text" name="lname">
														</div>
													</div>
												</div>

												<div class="form-group">
													<label>Email</label> <input class="form-control" placeholder="Enter your email" id="registerInputemail" type="text" name="email">
												</div>
												<div class="form-group">
													<label>Password</label> <input class="form-control" placeholder="Enter your password" id="password" type="password" name="password">
													<span id="result"></span>
												</div>
												<div class="form-group">
													<label>Confirm Password</label> <input class="form-control" placeholder="Enter your password" id="confirmpassword" type="password" name="confirm_password">
													<span  id="password_msg"></span>
												</div>
												<div class="form-group">
													<label for="term_conditions">
														By registering on this site, you agree to our use of cookies, <a href="#">Terms And Conditions<a/> & <a href="#">Privacy Policy<a/>.
														<input type="checkbox" id="term_conditions" name="terms_conditions">
													</label>
												</div>
												<button id="btn-email-proceed" disabled="disabled" class="btn btn-main-primary btn-block">Create Account</button>
											</form>
										</div>
										<div class="main-signup-footer mt-5">
											<p>Already have an account? <a href="{% url 'accounts:signin' %}">Sign In</a></p>
										</div>
									</div>
								</div>
							</div>
						</div><!-- End -->
					</div>
				</div><!-- End -->
			</div>
		</div>
	</div>


		<!-- JQuery min js -->
		<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>

		<!-- jquery validation plugin -->
		<script src="{% static 'assets/js/jquery-validation-1.19.3/dist/jquery.validate.js' %}"></script>

		<!-- Popper js -->
		<script src="{% static 'assets/plugins/popper/popper.min.js' %}"></script>

		<!-- Bootstrap Bundle js -->
		<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

		<!-- Ionicons js -->
		<script src="{% static 'assets/plugins/ionicons/ionicons.js' %}"></script>

		<!-- JQuery sparkline js -->
		<script src="{% static 'assets/plugins/jquery-sparkline/jquery.sparkline.min.js' %}"></script>

		<!-- Moment js -->
		<script src="{% static 'assets/plugins/moment/moment.js' %}"></script>

		<!-- Rating js -->
		<script src="{% static 'assets/plugins/rating/jquery.rating-stars.js' %}"></script>
		<script src="{% static 'assets/plugins/rating/jquery.barrating.js' %}"></script>

		<!-- Custom js -->
		<script src="{% static 'assets/js/custom.js' %}"></script>
	    <script src="https://cdn.jsdelivr.net/npm/exceptionless@v1.6.4/dist/exceptionless.min.js"></script>
	    <script>
		var client = exceptionless.ExceptionlessClient.default;
		client.config.apiKey = 'WDqMDPk1LJMrsi46mSug2Vk7A8lXFlDRlHCLO5UF';
		$("#registerInputemail").change(function(){
			var email=$(this).val();
			if(email!=""){
				$.ajax({
				  url:'{% url 'accounts:check_email_is_valid' %}',
				  type:'POST',
				  headers: {'X-CSRFToken': '{{ csrf_token }}'},
				  data:{email:email}
				})
				.done(function(response){
					if(response=="True"){
						$(".email_error").remove();
						$("<span class='email_error' style='padding: 3px;color: red;'>Email already exists !!</span>").insertAfter("#registerInputemail");
						$('#btn-email-proceed').attr('disabled','disabled');
					}else if(response=="Invalid"){
						client.submitException('invalid email');
						$(".email_error").remove();
						$("<span class='email_error' style='padding: 3px;color: red;'> Invalid Email !!</span>").insertAfter("#registerInputemail");
						$('#btn-email-proceed').attr('disabled','disabled');
					}
					else{
						$(".email_error").remove();
						$('#btn-email-proceed').removeAttr('disabled');
					}
				}).fail(function(){
					  console.log("failed");
				})
			}else{
				$(".email_error").remove();
			}
		});

	</script>
        <script>
            $(function() {
              $("form[name='agency_register']").validate({
                // Specify validation rules
                rules: {
                  // The key name on the left side is the name attribute
                  // of an input field. Validation rules are defined
                  // on the right side
                  fname: "required",
                  lname: "required",
                  email: {
                    required: true,
                    email: true
                  },
                  password: {
                  	required: true,
                    minlength: 8
                  },
                  confirm_password : {
                  	required: true,
                    minlength : 8,
                    equalTo : "#password"
                  },
                  terms_conditions:{
                  	 required:true,
                  }
                },
                // Specify validation error messages
                messages: {
                  fname: "Please enter your firstname",
                  lname: "Please enter your lastname",
                  password: {
                    required: "Please provide a password",
                    minlength: "Your password must be at least 8 characters long !"
                  },
                  confirm_password:{
                    equalTo : "Confirm Password must be same as password !"
                  },
                  terms_conditions:{
                  	required: "Please accept our terms & conditions and privacy policy.",
                  },
                  email: "Please enter a valid email address"
                },
                // Make sure the form is submitted to the destination defined
                // in the "action" attribute of the form when valid
                submitHandler: function(form) {
                  form.submit();
                }
              });
            });
        </script>
        <script>
            $(document).ready(function() {
                $('#password').keyup(function(){
                    $('#result').html(checkStrength($('#password').val()))
                })
                function checkStrength(password){

                    //initial strength
                    var strength = 0

                    //if the password length is less than 6, return message.
                    if (password.length < 6) {
                        $('#result').removeClass()
                        $('#result').addClass('short')
                        return 'Too short'
                    }

                    //length is ok, lets continue.

                    //if length is 8 characters or more, increase strength value
                    if (password.length > 7) strength += 1

                    //if password contains both lower and uppercase characters, increase strength value
                    if (password.match(/([a-z].*[A-Z])|([A-Z].*[a-z])/))  strength += 1

                    //if it has numbers and characters, increase strength value
                    if (password.match(/([a-zA-Z])/) && password.match(/([0-9])/))  strength += 1

                    //if it has one special character, increase strength value
                    if (password.match(/([!,%,&,@,#,$,^,*,?,_,~])/))  strength += 1

                    //if it has two special characters, increase strength value
                    if (password.match(/(.*[!,%,&,@,#,$,^,*,?,_,~].*[!,",%,&,@,#,$,^,*,?,_,~])/)) strength += 1

                    //now we have calculated strength value, we can return messages

                    //if value is less than 2
                    if (strength < 2 ) {
                        $('#result').removeClass()
                        $('#result').addClass('weak')
                        return 'Weak'
                    } else if (strength == 2 ) {
                        $('#result').removeClass()
                        $('#result').addClass('good')
                        return 'Good'
                    } else {
                        $('#result').removeClass()
                        $('#result').addClass('strong')
                        return 'Strong'
                    }
                }
            });
        </script>
	</body>
</html>